# Generated by Django 3.0.5 on 2020-06-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard', '0002_auto_20200505_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Published', max_length=12),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='theme',
            field=models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Green', 'Green'), ('Blue', 'Blue')], default='Light', max_length=20),
        ),
    ]
