# Generated by Django 3.0.5 on 2020-05-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Publicado', 'Publicado'), ('Borrardor', 'Borrador')], default='Borrador', max_length=15),
        ),
    ]
